services:
  hackhub-api-poc:
    container_name: hackhub-api-poc
    build: 
      context: .
    volumes:
      - .:/app
      - /app/node_modules    
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks: 
      - mynetwork

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks: 
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment: 
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - mynetwork
    tty: true
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  mynetwork:

volumes:
  postgres_data:
  pgadmin_data: